-- AlterTable
ALTER TABLE `Message` MODIFY `senderRole` ENUM('ADMIN', 'BUYER', 'DRIVER') NOT NULL;

-- AlterTable
ALTER TABLE `Profile` MODIFY `role` ENUM('ADMIN', 'BUYER', 'DRIVER') NOT NULL DEFAULT 'BUYER';
