import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | DISTRO",
  description:
    "How DISTRO collects, uses, and protects your data when you use our wholesale ordering service.",
};

export default function PrivacyPolicyPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12 text-ink">
      <header className="mb-10">
        <h1 className="font-grotesk text-4xl font-semibold tracking-tight">
          Privacy Policy
        </h1>
        <p className="mt-2 text-sm text-ink/60">Last updated: May 5, 2026</p>
      </header>

      <section className="space-y-4 leading-relaxed">
        <p>
          This Privacy Policy describes our policies and procedures on the
          collection, use, and disclosure of your information when you use the
          Service, and tells you about your privacy rights and how the law
          protects you.
        </p>
        <p>
          We use your Personal Data to provide and improve the Service. By
          using the Service, you agree to the collection and use of information
          in accordance with this Privacy Policy.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-grotesk text-2xl font-semibold">
          Interpretation and Definitions
        </h2>

        <h3 className="font-grotesk text-xl font-semibold mt-6">
          Interpretation
        </h3>
        <p>
          The words whose initial letters are capitalized have meanings defined
          under the following conditions. The following definitions shall have
          the same meaning regardless of whether they appear in singular or in
          plural.
        </p>

        <h3 className="font-grotesk text-xl font-semibold mt-6">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul className="list-disc space-y-3 pl-6">
          <li>
            <strong>Account</strong> means a unique account created for you to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by, or is under common control with a party, where
            &quot;control&quot; means ownership of 50% or more of the shares,
            equity interest, or other securities entitled to vote for election
            of directors or other managing authority.
          </li>
          <li>
            <strong>Application</strong> refers to DISTRO, the software program
            provided by the Company.
          </li>
          <li>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot;, or &quot;Our&quot;
            in this Privacy Policy) refers to DISTRO.
          </li>
          <li>
            <strong>Country</strong> refers to: Nepal.
          </li>
          <li>
            <strong>Device</strong> means any device that can access the
            Service such as a computer, a cell phone, or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> (or &quot;Personal Information&quot;)
            is any information that relates to an identified or identifiable
            individual. We use &quot;Personal Data&quot; and &quot;Personal
            Information&quot; interchangeably unless a law uses a specific term.
          </li>
          <li>
            <strong>Service</strong> refers to the Application.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service, or to assist
            the Company in analyzing how the Service is used.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-grotesk text-2xl font-semibold">
          Collecting and Using Your Personal Data
        </h2>

        <h3 className="font-grotesk text-xl font-semibold mt-6">
          Types of Data Collected
        </h3>

        <h4 className="font-grotesk text-lg font-semibold mt-4">
          Personal Data
        </h4>
        <p>
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul className="list-disc space-y-2 pl-6">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, state, province, ZIP/postal code, city</li>
        </ul>

        <h4 className="font-grotesk text-lg font-semibold mt-4">Usage Data</h4>
        <p>Usage Data is collected automatically when using the Service.</p>
        <p>
          Usage Data may include information such as your device&apos;s Internet
          Protocol address (e.g. IP address), browser type, browser version,
          the pages of our Service that you visit, the time and date of your
          visit, the time spent on those pages, unique device identifiers, and
          other diagnostic data.
        </p>
        <p>
          When you access the Service by or through a mobile device, we may
          collect certain information automatically, including, but not limited
          to, the type of mobile device you use, your mobile device&apos;s
          unique ID, the IP address of your mobile device, your mobile
          operating system, the type of mobile Internet browser you use, unique
          device identifiers, and other diagnostic data.
        </p>

        <h4 className="font-grotesk text-lg font-semibold mt-4">
          Information Collected while Using the Application
        </h4>
        <p>
          While using our Application, in order to provide features of our
          Application, we may collect, with your prior permission:
        </p>
        <ul className="list-disc space-y-2 pl-6">
          <li>Information regarding your location</li>
        </ul>
        <p>
          We use this information to provide features of our Service and to
          improve and customize our Service. The information may be uploaded to
          the Company&apos;s servers and/or a Service Provider&apos;s server,
          or it may simply be stored on your device. You can enable or disable
          access to this information at any time through your device settings.
        </p>

        <h3 className="font-grotesk text-xl font-semibold mt-6">
          Use of Your Personal Data
        </h3>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul className="list-disc space-y-3 pl-6">
          <li>
            <strong>To provide and maintain our Service</strong>, including to
            monitor the usage of our Service.
          </li>
          <li>
            <strong>To manage your account:</strong> to manage your
            registration as a user of the Service. The Personal Data you
            provide can give you access to different functionalities of the
            Service that are available to you as a registered user.
          </li>
          <li>
            <strong>For the performance of a contract:</strong> the development,
            compliance, and undertaking of the purchase contract for the
            products, items, or services you have purchased or of any other
            contract with us through the Service.
          </li>
          <li>
            <strong>To contact you:</strong> by email, telephone calls, SMS, or
            other equivalent forms of electronic communication, such as a
            mobile application&apos;s push notifications regarding updates or
            informative communications related to the functionalities,
            products, or contracted services, including security updates when
            necessary or reasonable for their implementation.
          </li>
          <li>
            <strong>To provide you</strong> with news, special offers, and
            general information about other goods, services, and events which
            we offer that are similar to those you have already purchased or
            inquired about, unless you have opted not to receive such
            information.
          </li>
          <li>
            <strong>To manage your requests:</strong> to attend and manage your
            requests to us.
          </li>
          <li>
            <strong>For business transfers:</strong> we may use your Personal
            Data to evaluate or conduct a merger, divestiture, restructuring,
            reorganization, dissolution, or other sale or transfer of some or
            all of our assets, whether as a going concern or as part of
            bankruptcy, liquidation, or similar proceeding, in which Personal
            Data held by us about our Service users is among the assets
            transferred.
          </li>
          <li>
            <strong>For other purposes:</strong> we may use your information
            for other purposes, such as data analysis, identifying usage
            trends, determining the effectiveness of our promotional campaigns,
            and to evaluate and improve our Service, products, services,
            marketing, and your experience.
          </li>
        </ul>

        <p>We may share your Personal Data in the following situations:</p>
        <ul className="list-disc space-y-3 pl-6">
          <li>
            <strong>With Service Providers:</strong> we may share your Personal
            Data with Service Providers to monitor and analyze the use of our
            Service and to contact you. These include Google (Maps, Places, and
            OAuth), Resend (email delivery), Sparrow SMS (SMS delivery), and
            Railway (hosting and database).
          </li>
          <li>
            <strong>For business transfers:</strong> we may share or transfer
            your Personal Data in connection with, or during negotiations of,
            any merger, sale of Company assets, financing, or acquisition of
            all or a portion of our business to another company.
          </li>
          <li>
            <strong>With Affiliates:</strong> we may share your Personal Data
            with our affiliates, in which case we will require those affiliates
            to honor this Privacy Policy.
          </li>
          <li>
            <strong>With business partners:</strong> we may share your Personal
            Data with our business partners to offer you certain products,
            services, or promotions.
          </li>
          <li>
            <strong>With your consent:</strong> we may disclose your Personal
            Data for any other purpose with your consent.
          </li>
        </ul>

        <h3 className="font-grotesk text-xl font-semibold mt-6">
          Retention of Your Personal Data
        </h3>
        <p>
          The Company will retain your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use your Personal Data to the extent necessary to comply
          with our legal obligations, resolve disputes, and enforce our legal
          agreements and policies.
        </p>
        <p>
          Where possible, we apply shorter retention periods and/or reduce
          identifiability by deleting, aggregating, or anonymizing data. The
          retention periods below are maximum periods (&quot;up to&quot;) and
          we may delete or anonymize data sooner when it is no longer needed:
        </p>
        <ul className="list-disc space-y-3 pl-6">
          <li>
            <strong>Account Information:</strong> retained for the duration of
            your account relationship plus up to 24 months after account
            closure.
          </li>
          <li>
            <strong>Customer Support Data:</strong> support tickets and chat
            transcripts retained up to 24 months from ticket closure for
            quality assurance and dispute resolution.
          </li>
          <li>
            <strong>Usage Data:</strong> application usage statistics and
            server logs retained up to 24 months for security monitoring,
            troubleshooting, and service improvements.
          </li>
        </ul>
        <p>
          We may retain Personal Data beyond the periods stated above where
          required by legal obligation, to establish or defend legal claims, at
          your explicit request, or due to technical limitations in backup
          systems. When retention periods expire, we securely delete or
          anonymize Personal Data.
        </p>

        <h3 className="font-grotesk text-xl font-semibold mt-6">
          Transfer of Your Personal Data
        </h3>
        <p>
          Your information, including Personal Data, is processed at the
          Company&apos;s operating offices and in any other places where the
          parties involved in the processing are located. This information may
          be transferred to — and maintained on — computers located outside of
          your state, province, country, or other governmental jurisdiction
          where the data protection laws may differ from those of your
          jurisdiction.
        </p>
        <p>
          The Company will take all steps reasonably necessary to ensure that
          your data is treated securely and in accordance with this Privacy
          Policy.
        </p>

        <h3 className="font-grotesk text-xl font-semibold mt-6">
          Delete Your Personal Data
        </h3>
        <p>
          You have the right to delete or request that we assist in deleting
          the Personal Data that we have collected about you. Our Service may
          give you the ability to delete certain information about you from
          within the Service.
        </p>
        <p>
          You may update, amend, or delete your information at any time by
          signing in to your account and visiting the account settings section
          that allows you to manage your personal information. You may also
          contact us to request access to, correct, or delete any Personal Data
          that you have provided to us.
        </p>
        <p>
          Please note, however, that we may need to retain certain information
          when we have a legal obligation or lawful basis to do so.
        </p>

        <h3 className="font-grotesk text-xl font-semibold mt-6">
          Disclosure of Your Personal Data
        </h3>

        <h4 className="font-grotesk text-lg font-semibold mt-4">
          Business Transactions
        </h4>
        <p>
          If the Company is involved in a merger, acquisition, or asset sale,
          your Personal Data may be transferred. We will provide notice before
          your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </p>

        <h4 className="font-grotesk text-lg font-semibold mt-4">
          Law Enforcement
        </h4>
        <p>
          Under certain circumstances, the Company may be required to disclose
          your Personal Data if required to do so by law or in response to
          valid requests by public authorities (e.g. a court or a government
          agency).
        </p>

        <h4 className="font-grotesk text-lg font-semibold mt-4">
          Other Legal Requirements
        </h4>
        <p>
          The Company may disclose your Personal Data in the good faith belief
          that such action is necessary to:
        </p>
        <ul className="list-disc space-y-2 pl-6">
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>
            Prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li>Protect the personal safety of users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>

        <h3 className="font-grotesk text-xl font-semibold mt-6">
          Security of Your Personal Data
        </h3>
        <p>
          The security of your Personal Data is important to us, but remember
          that no method of transmission over the Internet or method of
          electronic storage is 100% secure. While we strive to use commercially
          reasonable means to protect your Personal Data, we cannot guarantee
          its absolute security.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-grotesk text-2xl font-semibold">
          Detailed Information on the Processing of Your Personal Data
        </h2>
        <p>
          The Service Providers we use may have access to your Personal Data.
          These third-party vendors collect, store, use, process, and transfer
          information about your activity on our Service in accordance with
          their privacy policies.
        </p>

        <h3 className="font-grotesk text-xl font-semibold mt-6">
          Third-Party Service Providers
        </h3>
        <ul className="list-disc space-y-3 pl-6">
          <li>
            <strong>Google (Maps, Places, OAuth):</strong> used for location
            services, address selection, and account authentication on the web.
            Information gathered is held in accordance with the{" "}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="external nofollow noopener"
              className="text-brand-blue underline"
            >
              Google Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>Resend:</strong> used to deliver transactional emails such
            as OTP codes and order confirmations.
          </li>
          <li>
            <strong>Sparrow SMS:</strong> used to deliver SMS notifications and
            OTP codes within Nepal.
          </li>
          <li>
            <strong>Railway:</strong> used for application hosting and database
            services.
          </li>
        </ul>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-grotesk text-2xl font-semibold">
          Children&apos;s Privacy
        </h2>
        <p>
          Our Service does not address anyone under the age of 16. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 16. If you are a parent or guardian and you are
          aware that your child has provided us with Personal Data, please
          contact us. If we become aware that we have collected Personal Data
          from anyone under the age of 16 without verification of parental
          consent, we take steps to remove that information from our servers.
        </p>
        <p>
          DISTRO is intended for use by adults aged 18 and over for the
          purchase of wholesale goods, including age-restricted products.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-grotesk text-2xl font-semibold">
          Links to Other Websites
        </h2>
        <p>
          Our Service may contain links to other websites that are not operated
          by us. If you click on a third-party link, you will be directed to
          that third party&apos;s site. We strongly advise you to review the
          Privacy Policy of every site you visit. We have no control over and
          assume no responsibility for the content, privacy policies, or
          practices of any third-party sites or services.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-grotesk text-2xl font-semibold">
          Changes to this Privacy Policy
        </h2>
        <p>
          We may update our Privacy Policy from time to time. We will notify
          you of any changes by posting the new Privacy Policy on this page and
          updating the &quot;Last updated&quot; date at the top.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-grotesk text-2xl font-semibold">Contact Us</h2>
        <p>
          If you have any questions about this Privacy Policy, you can contact
          us:
        </p>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            By email:{" "}
            <a
              href="mailto:ankritsapkota12345@gmail.com"
              className="text-brand-blue underline"
            >
              ankritsapkota12345@gmail.com
            </a>
          </li>
          <li>
            By phone:{" "}
            <a href="tel:+9779851017265" className="text-brand-blue underline">
              +977 9851017265
            </a>
          </li>
        </ul>
      </section>
    </main>
  );
}